project:
  type: website
  output-dir: docs

website:
  title: "Luke Simon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: hof.qmd
        text: Wikipedia HOF
      - href: resume.qmd
        text: Resume/CV

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true



