project:
  type: website
  output-dir: docs

website:
  title: "Luke Simon"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: hof.qmd
        text: Wikipedia HOF
      - href: resume.qmd
        text: Resume/CV

format:
  html:
    theme: 
        - styles.scss
        - darkly
    mainfont: Merriweather
    toc: true



